const buttonsNames = {
    memoryClear: 'MC',
    memoryAdd: 'M+',
    memorySubtract: 'M-',
    memoryRecall: 'MR',
    allClean: 'AC',
    changeSign: '+/-',
    percent: '%',
    divide: '/',
    multiply: '*',
    minus: '-',
    plus: '+',
    equal: '=',
    dot: '.',
    zero: '0',
    one: '1',
    two: '2',
    three: '3',
    four: '4',
    five: '5',
    six: '6',
    seven: '7',
    eight: '8',
    nine: '9',
    square: 'x^2',
    cube: 'x^3',
    numberPower: 'x^y',
    tenPower: '10^x',
    reverse: '1/x',
    squareRoot: `\u{0221A}x`,
    cubeRoot: `\u{0221B}x`,
    powerRoot: `x\u{0221A}y`,
    factorial: '!x',
};

export default buttonsNames;
